Table users {
  id int [pk]
  name varchar
  email varchar
}

Table boards {
  id int [pk]
  name varchar
  user_id int [not null]
}

Ref: boards.user_id > users.id

Table columns {
  id int [pk]
  name varchar
  board_id int [not null]
}

Ref: columns.board_id > boards.id

Table tasks {
  id int [pk]
  title varchar
  column_id int [not null]
}

Ref: tasks.column_id > columns.id

Table subtasks {
  id int [pk]
  title varchar
  task_id int [not null]
}

Ref: subtasks.task_id > tasks.id